Work in progress

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -38,11 +38,11 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_REGION: ${{ secrets.AWS_REGION }}
         run: |
-          bucketstatus=$(aws s3api head-bucket --bucket "terraform-ecs-demonstration-remote-state-bucket" 2>&1)
-#          if echo "${bucketstatus}" | grep 'Not Found';
-#          then
-#          echo "Bucket doesn't exist, creating the bucket...";
-#
+          bucketstatus=$(aws s3api head-bucket --bucket terraform-ecs-demonstration-remote-state-bucket 2>&1 || true)
+          if echo "${bucketstatus}" | grep 'Not Found';
+          then
+          echo "Bucket doesn't exist, creating the bucket...";
+
 #          cd infrastructure/s3-bucket-for-terraform-remote-state
 #
 #          terraform init
